import type { EquipmentSubType } from '@/lib/equipment-specs'

export const EQUIPMENT_KEYWORDS: Record<EquipmentSubType, string[]> = {
  centrifuge: [
    '냉각 원심분리기',
    '마이크로 원심분리기',
    '고속 원심분리기',
    '초고속 초원심분리기',
    '저속 원심분리기',
    '플레이트 원심분리기',
    '미니 원심분리기',
    '진공 원심농축기',
  ],
  pcr: [
    '일반 PCR 기기 (써모사이클러)',
    '실시간 PCR (qPCR) 기기',
    'Digital PCR 기기',
    '그래디언트 PCR 기기',
    '멀티채널 써모사이클러',
    '냉각 PCR 블록',
  ],
  microscope: [
    '형광 현미경 (Fluorescence)',
    '위상차 현미경',
    '공초점 레이저 현미경 (Confocal)',
    '도립 현미경 (Inverted)',
    '실체 현미경 (Stereo)',
    '전자 현미경 (SEM)',
    '전자 현미경 (TEM)',
    '광시트 현미경 (Light Sheet)',
    '슈퍼레졸루션 현미경',
  ],
  spectro: [
    'UV-Vis 분광광도계',
    'NanoDrop (극소량 핵산·단백질 정량)',
    '형광 분광광도계',
    'FTIR 분광계',
    '라만 분광계',
    'Microplate Reader (ELISA 판독기)',
    'BCA 단백질 정량 시스템',
    'ICP-MS',
  ],
  cell_culture: [
    'CO₂ 인큐베이터',
    '생물안전작업대 (BSC Class II)',
    '세포 계수기 (자동)',
    '바이오리액터',
    '세포 동결 보관 시스템',
    '유세포 분석기 (Flow Cytometer)',
    '세포 분류기 (Cell Sorter)',
    '라이브셀 이미징 시스템',
  ],
  chromatography: [
    'HPLC 시스템',
    'UHPLC 시스템',
    'FPLC / AKTA 정제 시스템',
    'GC (기체 크로마토그래피)',
    'LC-MS/MS 시스템',
    'GPC/SEC 시스템',
    '이온 크로마토그래피',
    '플래시 크로마토그래피',
  ],
  cold_storage: [
    '-80°C 초저온 냉동고',
    '-20°C 냉동고 (실험실용)',
    '4°C 냉장고 (실험실용)',
    '액체질소 탱크 (Dewar)',
    '냉동 건조기 (동결건조기)',
    'LN2 자동 보충 시스템',
  ],
  organoid: [
    '3D 바이오프린터 (고분해능 세포프린팅)',
    '오가노이드 배양 바이오리액터',
    '하이드로겔 기반 오가노이드 배양 시스템',
    '오가노이드 라이브 이미징 시스템',
    '마이크로플루이딕스 기반 오가노이드 칩 (Organ-on-a-Chip)',
    '고처리량 오가노이드 스크리닝 플랫폼 (HTS)',
    '오가노이드 동결 보존 시스템',
  ],
  animal_experiment: [
    '동물 흡입 마취기 (이소플루란용)',
    '뇌정위 고정장치 — 마우스용 (Stereotaxic Frame)',
    '뇌정위 고정장치 — 랫드용',
    '소동물 대사 측정 케이지 (Metabolic Cage)',
    '오픈필드 행동분석 시스템 (Open Field Test)',
    '수중미로 행동분석 장치 (Morris Water Maze)',
    '공포 조건화 장치 (Fear Conditioning)',
    '소동물 생체 이미징 시스템 (IVIS Spectrum)',
    '소동물 방사선 조사기 (γ-irradiator)',
    '동물용 혈액분석기 (CBC, Blood Chemistry)',
  ],
  pretreatment: [
    '분쇄기 (Ball Mill / Bead Mill)',
    '균질화 장비 (Homogenizer)',
    '고속 분쇄·균질기 (TissueLyser / FastPrep)',
    '고압 균질기 (High-pressure Homogenizer)',
    '고체상 추출 장치 (SPE Manifold)',
    '액액추출 시스템 (LLE)',
    '가속용매추출기 (ASE / PLE)',
    '마이크로웨이브 소화기 (Microwave Digester)',
    '핫블록 소화기 (Hot Block Digester)',
    '질소 농축 장비 (N2 Evaporator)',
    '로터리 에바포레이터 (Rotary Evaporator)',
    '진공 여과 장치 (Vacuum Filtration)',
    '한외여과 장치 (Ultrafiltration, UF)',
    '볼텍스 믹서 (Vortex Mixer)',
    '자동 액체 처리기 (Liquid Handler)',
    '자동화 전처리 워크스테이션',
  ],
  other: [
    '고압증기멸균기 (Autoclave)',
    '진탕배양기 (Shaking Incubator)',
    '전기영동 장치 (젤 전기영동)',
    '웨스턴블롯 트랜스퍼 장치',
    '겔 이미징 시스템',
    'pH 미터',
    '초음파 파쇄기 (Sonicator)',
    '동결건조기 (Lyophilizer)',
    '분쇄기 (Homogenizer)',
    '나노입자 크기 분석기 (DLS)',
  ],
}
